name: 'Kemocade VRC Group Maker Action'
description: 'GitHub Action for automatically making VRChat Groups'
branding:
  icon: globe
  color: blue
inputs:
  username:
    description: 'VRChat Username'
    required: true
  password:
    description: 'VRChat Password'
    required: true
  key:
    description: 'VRChat 2FA secret key'
    required: true
  name:
    description: 'Desired VRChat Group Name'
    required: true
  shortcode:
    description: 'Desired VRChat Group Shortcode'
    required: true
  discriminators:
    description: 'Desired VRChat Group Discriminators'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-u'
  - ${{ inputs.username }}
  - '-p'
  - ${{ inputs.password }}
  - '-k'
  - ${{ inputs.key }}
  - '-n'
  - ${{ inputs.name }}
  - '-s'
  - ${{ inputs.shortcode }}
  - '-d'
  - ${{ inputs.discriminators }}